# .dev means this docker file is only used for development, not production
FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# copy source destination files from a local source location (frontend directory) to the destination in the Docker container
COPY . .

CMD ["npm", "run", "start"]